package elements;

import assets.textures.Texture2D;
import elements.containers.GUIContainerElement;
import gui_core.GUIManager;
import gui_core.GUIMatrixManager;
import math.matrices.Matrix44f;
import math.matrices.advanced.MatrixInversion44f;
import math.vectors.Vector4f;
import rendering.shapes.GUIShape;

public abstract class GUIElement implements Clickable {
	
	//The id of this element. The id is generated by the GUIManager and assigned to the element
	private final int ID;
	
	//The parent of this element
	private GUIContainerElement parent;
	
	//The dimensions of this element
	private float x, y, width, height;
	
	//The attributes of this element
	private boolean visible, resizable, movable, closeable;
	
	//The shape of this element
	private GUIShape shape;
	
	//The transformation matrix of this element
	private Matrix44f renderingMatrix;
	
	//The inverted transformation matrix
	private Matrix44f invertedRenderingMatrix;
	
	//The texture for rendering this element
	private Texture2D texture;
	
	//The color for rendering this element
	private Vector4f color;
	
	//Have there been any changes to this elements position and size?
	private boolean changed;
		
		
	
	private GUIElement(GUIShape shape, Texture2D texture, Vector4f color, float x, float y, float width, float height) {
		
		//If the GUIManager isn't initialized yet, do it now.
		if (!GUIManager.isInitialized()) {
			GUIManager.init();
		}
		
		this.parent = null;
		
		this.x = x;
		this.y = y;
		this.width = width;
		this.height = height;
		
		this.ID = GUIManager.generateID();
		
		this.changed = true;
		
		this.shape = shape;
		this.texture = texture;
		this.color = color;
		
		this.resizable = false;
		this.visible = true;
		this.movable = false;
		this.closeable = true;
		
		this.renderingMatrix = GUIMatrixManager.generateRenderingMatrix(x, y, width, height);
		this.invertedRenderingMatrix = MatrixInversion44f.generateMultiplicativeInverse(renderingMatrix);
		
	}

	
	public GUIElement(GUIShape shape, Texture2D texture, float x, float y, float width, float height) {
		
		this(shape, texture, null, x, y, width, height);
		
	}
	
	
	public GUIElement(GUIShape shape, Vector4f color, float x, float y, float width, float height) {
		
		this(shape, null, color, x, y, width, height);
		
	}
	
	
	public void render() {
		
		if (!visible) {
			return;
		}

		shape.render(texture, color, renderingMatrix);
		
	}
	
	
	public void update() {
		
		Matrix44f parentMatrix = new Matrix44f();
		Matrix44f invertedParentMatrix = new Matrix44f();
		
			
		this.renderingMatrix = GUIMatrixManager.generateRenderingMatrix(x, y, width, height);

		
		if (parent != null) {
			parentMatrix = parent.getRenderingMatrix();
			invertedParentMatrix = parent.getInvertedRenderingMatrix();
		}
		
		this.renderingMatrix = renderingMatrix.times(parentMatrix);
		this.invertedRenderingMatrix = invertedParentMatrix.times(MatrixInversion44f.generateMultiplicativeInverse(renderingMatrix));
		
	}
	
	
	/**
	 * 
	 * Processes the mouse input and checks if it effects this element.
	 * 
	 * @param cursorX The cursor x position.
	 * @param cursorY The cursor y position.
	 * @param leftMouseButtonDown Is the left mouse button pressed?
	 * @param rightMouseButtonDown Is the right mouse button pressed?
	 * @return Returns if this element is hit by this cursor.
	 */
	public boolean processInput(float cursorX, float cursorY, boolean leftMouseButtonDown, boolean rightMouseButtonDown) {
		
		//Compute the local space coordinates of the cursor position
		Vector4f vec = new Vector4f(cursorX, cursorY, 0.9f, 1f);
		vec = this.getInvertedRenderingMatrix().times(vec);
		
		if (shape.isHit(vec.getA(), vec.getB())) {
			
			if (leftMouseButtonDown) {
				onClick();
			} else {
				onHover();
			}
			
			return true;
			
		}
		
		return false;
		
	}
	
	
	public void resize(float width, float height) {
		
		if (!resizable) {
			return;
		}
		
		this.width = width;
		
		this.height = height;
		
		changed = true;
		
	}
	
	
	public void reposition(float x, float y) {
		
		if (!movable) {
			return;
		}
		
		this.x = x;
		
		this.y = y;
		
		changed = false;
		
	}
	

	public void setParent(GUIContainerElement element) {
		this.parent = element;
	}
	
	
	public boolean isVisible() {
		return visible;
	}


	public void setVisible(boolean visible) {
		this.visible = visible;
	}


	public boolean isResizable() {
		return resizable;
	}


	public void setResizable(boolean resizable) {
		this.resizable = resizable;
	}


	public boolean isMovable() {
		return movable;
	}


	public void setMovable(boolean movable) {
		this.movable = movable;
	}


	public boolean isCloseable() {
		return closeable;
	}


	public void setCloseable(boolean closeable) {
		this.closeable = closeable;
	}
	
	
	public GUIShape getShape() {
		return shape;
	}
	
	
	public void setColor(Vector4f color) {
		this.color = color;
	}


	public float getX() {
		return x;
	}


	public float getY() {
		return y;
	}


	public float getWidth() {
		return width;
	}


	public float getHeight() {
		return height;
	}
	
	
	public Matrix44f getRenderingMatrix() {
		return renderingMatrix;
	}
	
	
	public Matrix44f getInvertedRenderingMatrix() {
		return invertedRenderingMatrix;
	}
	
	public void delete() {		
		parent.remove(this);
				
		onClose();
		
		this.delete();
	}

}
