package fundamental;

import java.util.LinkedList;
import java.util.List;

import function.GUIEventListener;
import gui_core.Input;
import layout.IGUILayoutNode;
import layout.IGUILayoutNode.Alignment;
import layout.IGUILayoutNode.Direction;
import layout.yoga.GUIYogaNode;
import rendering.shapes.GUIShape;

public abstract class Element {	
	
	//The Yoga ID for this element.
	protected final IGUILayoutNode node;
	
	private GUIShape shape;
	
	//Cursor input event listeners.
	private boolean isTargeted;
	private List<GUIEventListener> mouseEnterListeners;
	private List<GUIEventListener> mouseStayListeners;
	private List<GUIEventListener> mouseLeaveListeners;
	
	//Left mouse button event listeners.
	private boolean isLeftClicked;
	private List<GUIEventListener> leftMouseButtonDownListeners;
	private List<GUIEventListener> leftMouseButtonHoldListeners;
	private List<GUIEventListener> leftMouseButtonReleaseListeners;
	
	private boolean isRightClicked;
	private List<GUIEventListener> rightMouseButtonDownListeners;
	private List<GUIEventListener> rightMouseButtonHoldListeners;
	private List<GUIEventListener> rightMouseButtonReleaseListeners;
	
	private List<GUIEventListener> dragListener;
	
	private boolean active = true;
	private boolean visible = true;
	
	
	/**
	 * 
	 * @param width The width of the element in pixels.
	 * @param height The height of the element in pixels.
	 */
	protected Element(GUIShape shape, int width, int height) {
		node = GUIYogaNode.createNode();
		
		this.shape = shape;
		setWidth(width);
		setHeight(height);
		init();
	}
	
	
	/**
	 * 
	 * @param widthPercent The width of the element in relation to the parent.
	 * @param heightPercent The height of the element in relation to the parent.
	 */
	protected Element(GUIShape shape, float widthPercent, float heightPercent) {
		node = GUIYogaNode.createNode();
		
		this.shape = shape;
		setWidth(widthPercent);
		setHeight(heightPercent);
		init();
	}
	
	
	/**
	 * Init all event listener lists.
	 */
	private void init() {
		mouseEnterListeners = new LinkedList<GUIEventListener>();
		mouseStayListeners = new LinkedList<GUIEventListener>();
		mouseLeaveListeners = new LinkedList<GUIEventListener>();
		
		leftMouseButtonDownListeners = new LinkedList<GUIEventListener>();
		leftMouseButtonHoldListeners = new LinkedList<GUIEventListener>();
		leftMouseButtonReleaseListeners = new LinkedList<GUIEventListener>();
		
		rightMouseButtonDownListeners = new LinkedList<GUIEventListener>();
		rightMouseButtonHoldListeners = new LinkedList<GUIEventListener>();
		rightMouseButtonReleaseListeners = new LinkedList<GUIEventListener>();
		
		dragListener = new LinkedList<GUIEventListener>();
	}
	
	
	/**
	 * 
	 * @return Returns the layout node for this element.
	 */
	public IGUILayoutNode getLayoutID() {
		return node;
	}
	
	
	/**
	 * 
	 * Sets the elements x position, thus overriding the value generated by the layout.
	 * 
	 * @param x The new local x position measured in pixel.
	 */
	public void setLocalXPosition(int x) {
		node.setLocalXCoordinate(x);
	}
	
	
	/**
	 * 
	 * Sets the elements x position, thus overriding the value generated by the layout.
	 * 
	 * @param percent The new local x position relative to the width of the parent node.
	 */
	public void setLocalXPosition(float percent) {
		node.setLocalXCoordinate(percent);
	}
	
	
	/**
	 * 
	 * @return Returns the x coordinate of the upper left corner of this element. Note that this
	 * isn't the global position but the offset relative to the parent's position.
	 */
	public int getLocalXPosition() {
		return node.getLocalXCoordinate();
	}
	
	
	/**
	 * 
	 * @param parentX The parent's x coordinate on the screen.
	 * @return Return this element's x coordinate on the screen.
	 */
	public int getGlobalXPosition() {
		return node.getGlobalXCoordinate();
	}
	
	
	/**
	 * 
	 * Sets the elements x position, thus overriding the value generated by the layout.
	 * 
	 * @param y The new local y position.
	 */
	public void setLocalYPosition(int y) {
		node.setLocalYCoordinate(y);
	}
	
	
	/**
	 * 
	 * Sets the elements x position, thus overriding the value generated by the layout.
	 * 
	 * @param percent The new local x position relative to the width of the parent node.
	 */
	public void setLocalYPosition(float percent) {
		node.setLocalYCoordinate(percent);
	}
	
	
	/**
	 * 
	 * @return Returns the y coordinate of the upper left corner of this element. Note that this
	 * isn't the global position but the offset relative to the parent's position.
	 */
	public int getLocalYPosition() {
		return node.getLocalYCoordinate();
	}
	
	
	/**
	 * 
	 * @param parentY The parent's y coordinate on the screen.
	 * @return Return this element's y coordinate on the screen.
	 */
	public int getGlobalYPosition() {
		return node.getGlobalYCoordinate();
	}
	
	
	/**
	 * 
	 * @param width The width of the element in pixels.
	 */
	public void setWidth(int width) {
		node.setWidth(width);
	}
	
	
	/**
	 * 
	 * @param percent The width of the element in relation to the parent.
	 */
	public void setWidth(float percent) {
		node.setWidth(percent);
	}
	
	
	/**
	 * 
	 * @return Returns the width of the element as it was calculated by Yoga.
	 */
	public int getWidth() {
		return node.getWidth();
	}
	
	
	/**
	 * 
	 * @param height The height of the element in pixels.
	 */
	public void setHeight(int height) {
		node.setHeight(height);
	}
	
	
	/**
	 * 
	 * @param percent The height of the element in relation to the parent.
	 */
	public void setHeight(float percent) {
		node.setHeight(percent);
	}
	
	
	/**
	 * 
	 * @return Returns the height of the element as it was calculated by Yoga.
	 */
	public int getHeight() {
		return node.getHeight();
	}
	
	
	public void setMargin(Direction direction, int margin) {
		node.setMargin(direction, margin);
	}
	
	
	public void setMargin(Direction direction, float percent) {
		node.setMargin(direction, percent);
	}
	
	
	public void setPadding(Direction direction, int padding) {
		node.setPadding(direction, padding);
	}
	
	
	public void setPadding(Direction direction, float percent) {
		node.setPadding(direction, percent);
	}
	
	
	public void setAlignment(Alignment align) {
		node.setAlignment(align);
	}
	
	
	/**
	 * 
	 * @return Returns the shape of this element.
	 */
	public GUIShape getShape() {
		return shape;
	}
	
	
	/**
	 * 
	 * @param shape Sets the shape of this element.
	 */
	public void setShape(GUIShape shape) {
		this.shape = shape;
	}
	
	
	/**
	 * 
	 * Renders the Element onto the screen.
	 * 
	 * @param parentX The x coordinate of the parent element.
	 * @param parentY The y coordinate of the parent element.
	 */
	public void render(int parentX, int parentY) {
		if (visible) {
			int x = parentX + getLocalXPosition();
			int y = parentY + getLocalYPosition();
			
			shape.render(x, y, getWidth(), getHeight());
		}
	}
	
	
	/**
	 * 
	 * Check if the cursor is currently targeting this element.
	 * 
	 * @param parentX The x coordinate of the parent element.
	 * @param parentY The y coordinate of the parent element.
	 * @param cursorX The x coordinate of the cursor.
	 * @param cursorY The y coordinate of the cursor.
	 * @return Returns true if the cursor is targeting this element.
	 */
	public boolean isTargeted(int parentX, int parentY, int cursorX, int cursorY) {
		int x = parentX + getLocalXPosition();
		int y = parentY + getLocalYPosition();
		
		return shape.isTargeted(x, y, getWidth(), getHeight(), cursorX, cursorY);
	}
	
	
	/**
	 * Updates the state that marks this element as targeted.
	 */
	private void updateTargetingState(Input input) {
		if (!isTargeted) {
			onMouseEnter(input);
			isTargeted = true;
		} else {
			onMouseStay(input);
		}
	}
	
	
	private void updateLeftMouseButtonState(Input input) {
		//Check if the left mouse button is actually pressed down.
		if (input.leftMouseButton) {
			if (!isLeftClicked) {
				onLeftMouseButtonDown(input);
				isLeftClicked = true;
			} else {
				onLeftMouseButtonHold(input);
				onDrag(input);
			}
		} else {
			if (isLeftClicked) {
				onLeftMouseButtonRelease(input);
				isLeftClicked = false;
			}
		}
	}
	
	
	private void updateRightMouseButtonState(Input input) {
		//Check if the right mouse button is actually pressed down.
		if (input.rightMouseButton) {
			if (!isRightClicked) {
				onRightMouseButtonDown(input);
				isRightClicked = true;
			} else {
				onRightMouseButtonHold(input);
			}
		} else {
			if (isRightClicked) {
				onRightKeyRelease(input);
				isRightClicked = false;
			}
		}	
	}
	
	
	protected void updateInputStates(Input input) {
		updateTargetingState(input);
		updateLeftMouseButtonState(input);
		updateRightMouseButtonState(input);
	}
	
	
	/**
	 * Cleans up the input state when the cursor isn't targeting 
	 * this element anymore.
	 * 
	 * @param input The current input state.
	 */
	protected void resetInputStates(Input input) {		
		if (isTargeted) {
			onMouseLeave(input);
			isTargeted = false;
		}
		
		if (isLeftClicked) {
			onLeftMouseButtonRelease(input);
			isLeftClicked = false;
		}
		
		if (isRightClicked) {
			onRightKeyRelease(input);
			isRightClicked = false;
		}
	}
	
	
	/**
	 * 
	 * This method handles everything regarding input.
	 * 
	 * @param parentX The x coordinate of the parent element.
	 * @param parentY The y coordinate of the parent element.
	 * @param cursorX The x coordinate of the cursor.
	 * @param cursorY The y coordinate of the cursor.
	 * @return Returns true if the user is currently interacting with this element.
	 */
	public boolean processInput(int parentX, int parentY, Input input) {
		if (!active) {
			return false;
		}
		
		if (isTargeted(parentX, parentY, input.cursorX, input.cursorY)) {
			//Update all states.
			updateInputStates(input);
			
			return true;
		} else {
			//Reset all states.
			resetInputStates(input);
			
			return false;
		}
	}
	
	
	protected void addMouseEnterListener(GUIEventListener listener) {
		mouseEnterListeners.add(listener);
	}
	
	
	private void onMouseEnter(Input input) {
		mouseEnterListeners.forEach((e) -> e.execute(input));
	}
	
	
	protected void addMouseStayListener(GUIEventListener listener) {
		mouseStayListeners.add(listener);
	}
	
	
	private void onMouseStay(Input input) {
		mouseStayListeners.forEach((e) -> e.execute(input));
	}
	
	
	protected void addMouseLeaveListener(GUIEventListener listener) {
		mouseLeaveListeners.add(listener);
	}
	
	
	private void onMouseLeave(Input input) {
		mouseLeaveListeners.forEach((e) -> e.execute(input));
	}
	
	
	protected void addLeftMouseButtonDownListener(GUIEventListener listener) {
		leftMouseButtonDownListeners.add(listener);
	}
	
	
	private void onLeftMouseButtonDown(Input input) {
		leftMouseButtonDownListeners.forEach((e) -> e.execute(input));
	}
	
	
	protected void addLeftMouseButtonHoldListener(GUIEventListener listener) {
		leftMouseButtonHoldListeners.add(listener); 
	}
	
	
	private void onLeftMouseButtonHold(Input input) {
		leftMouseButtonHoldListeners.forEach((e) -> e.execute(input));
	}
	
	
	protected void addLeftMouseButtonReleaseListener(GUIEventListener listener) {
		leftMouseButtonReleaseListeners.add(listener);
	}
	
	
	private void onLeftMouseButtonRelease(Input input) {
		leftMouseButtonReleaseListeners.forEach((e) -> e.execute(input));
	}
	
	
	protected void addRightMouseButtonDownListener(GUIEventListener listener) {
		rightMouseButtonDownListeners.add(listener);
	}
	
	
	private void onRightMouseButtonDown(Input input) {
		rightMouseButtonDownListeners.forEach((e) -> e.execute(input));
	}
	
	
	protected void addRightMouseButtonHoldListener(GUIEventListener listener) {
		rightMouseButtonHoldListeners.add(listener);
	}
	
	
	private void onRightMouseButtonHold(Input input) {
		rightMouseButtonHoldListeners.forEach((e) -> e.execute(input));
	}
	
	
	protected void addRightMouseButtonReleaseListener(GUIEventListener listener) {
		rightMouseButtonReleaseListeners.add(listener);
	}
	
	
	private void onRightKeyRelease(Input input) {
		rightMouseButtonReleaseListeners.forEach((e) -> e.execute(input));
	}
	
	
	public void addDragListener(GUIEventListener listener) {
		dragListener.add(listener);
	}
	
	
	private void onDrag(Input input) {
		dragListener.forEach((e) -> e.execute(input));
	}
	
	
	public void setActive(boolean active) {
		this.active = active;
	}
	
	
	public void setVisible(boolean active) {
		this.active = false;
		this.visible = false;
	}

	
	public boolean equals(Element element) {
		return node.equals(element.node);
	}
	
	
	public void delete() {
		((GUIYogaNode)node).delete();
	}
	
}
